# Generated by Django 4.1.7 on 2023-04-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogs',
            new_name='Blog',
        ),
    ]
